/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author krishchandarana
 */
public class DisplaySpecificEmployee extends javax.swing.JFrame {

    private MyHashTable theMainHashTable;
    private FTE DisplayEmployeeFTE;
    private PTE DisplayEmployeePTE;

    
    public void setTheMainHashTable(MyHashTable theRefValueHT){
        theMainHashTable = theRefValueHT;
    }
    
    public DisplaySpecificEmployee() {
        initComponents();
        noEmployeeFound.setVisible(false);
        SpecificEmployeePanel.setVisible(false);
        PTEPanel.setVisible(false);
        FTEPanel.setVisible(false);
        HW.setEditable(false);
        HPW.setEditable(false);
        WPY.setEditable(false);
        EmpType.setEditable(false);
        FirstName.setEditable(false);
        LastName.setEditable(false);
        EmpGender.setEditable(false);
        EmpWorkLoc.setEditable(false);
        EmpRole.setEditable(false);
        NetIncome.setEditable(false);
        DeductRate.setEditable(false);
        YearlySalary.setEditable(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        userInput = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        DisplayEmployee = new javax.swing.JButton();
        ExitProgram = new javax.swing.JButton();
        noEmployeeFound = new javax.swing.JLabel();
        SpecificEmployeePanel = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        FirstName = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        LastName = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        EmpType = new javax.swing.JTextField();
        NetIncome = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        EmpWorkLoc = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        EmpGender = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        EmpRole = new javax.swing.JTextField();
        PTEPanel = new javax.swing.JPanel();
        WPYLabel = new javax.swing.JLabel();
        WPY = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        HPW = new javax.swing.JTextField();
        HW = new javax.swing.JTextField();
        FTEPanel = new javax.swing.JPanel();
        YearlySalary = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        DeductRate = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 99, 71)));

        userInput.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jLabel8.setText("Enter Employee Number Below:");

        DisplayEmployee.setBackground(new java.awt.Color(255, 255, 255));
        DisplayEmployee.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        DisplayEmployee.setText("Display Employee");
        DisplayEmployee.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 99, 71), 1, true));
        DisplayEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisplayEmployeeActionPerformed(evt);
            }
        });

        ExitProgram.setBackground(new java.awt.Color(255, 255, 255));
        ExitProgram.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        ExitProgram.setText("Back");
        ExitProgram.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 99, 71), 1, true));
        ExitProgram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitProgramActionPerformed(evt);
            }
        });

        noEmployeeFound.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        noEmployeeFound.setText("*CANNOT FIND EMPLOYEE*");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(noEmployeeFound)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(DisplayEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ExitProgram, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(userInput, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel8)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(userInput, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(DisplayEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ExitProgram, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(noEmployeeFound)
                .addGap(155, 155, 155))
        );

        SpecificEmployeePanel.setBackground(new java.awt.Color(255, 255, 255));
        SpecificEmployeePanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 99, 71)));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jLabel10.setText("First Name:");

        FirstName.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jLabel11.setText("Last Name:");

        LastName.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jLabel12.setText("Employee Type:");

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jLabel13.setText("Annual Net Income (In Dollars):");

        EmpType.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N

        NetIncome.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jLabel14.setText("Employee Work Location:");

        EmpWorkLoc.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jLabel15.setText("Employee Gender:");

        EmpGender.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jLabel16.setText("Employee Role:");

        EmpRole.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N

        PTEPanel.setBackground(new java.awt.Color(255, 255, 255));

        WPYLabel.setBackground(new java.awt.Color(255, 255, 255));
        WPYLabel.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        WPYLabel.setText("Weeks Per Year:");

        WPY.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N

        jLabel18.setBackground(new java.awt.Color(255, 255, 255));
        jLabel18.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jLabel18.setText("Hours Per Week:");

        jLabel19.setBackground(new java.awt.Color(255, 255, 255));
        jLabel19.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jLabel19.setText("Hourly Wage:");

        HPW.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N

        HW.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N

        javax.swing.GroupLayout PTEPanelLayout = new javax.swing.GroupLayout(PTEPanel);
        PTEPanel.setLayout(PTEPanelLayout);
        PTEPanelLayout.setHorizontalGroup(
            PTEPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PTEPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PTEPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(HW, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PTEPanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel19)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PTEPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(HPW, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PTEPanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel18)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(PTEPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(WPY, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PTEPanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(WPYLabel))))
        );
        PTEPanelLayout.setVerticalGroup(
            PTEPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PTEPanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(PTEPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PTEPanelLayout.createSequentialGroup()
                        .addComponent(WPYLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(WPY, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PTEPanelLayout.createSequentialGroup()
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(HW, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PTEPanelLayout.createSequentialGroup()
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(HPW, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        FTEPanel.setBackground(new java.awt.Color(255, 255, 255));

        YearlySalary.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N

        jLabel20.setBackground(new java.awt.Color(255, 255, 255));
        jLabel20.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jLabel20.setText("Yearly Salary (Without Deductions)");

        javax.swing.GroupLayout FTEPanelLayout = new javax.swing.GroupLayout(FTEPanel);
        FTEPanel.setLayout(FTEPanelLayout);
        FTEPanelLayout.setHorizontalGroup(
            FTEPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FTEPanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel20)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FTEPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(YearlySalary, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        FTEPanelLayout.setVerticalGroup(
            FTEPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FTEPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(YearlySalary, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        DeductRate.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N

        jLabel17.setBackground(new java.awt.Color(255, 255, 255));
        jLabel17.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jLabel17.setText("Deduct Rate:");

        javax.swing.GroupLayout SpecificEmployeePanelLayout = new javax.swing.GroupLayout(SpecificEmployeePanel);
        SpecificEmployeePanel.setLayout(SpecificEmployeePanelLayout);
        SpecificEmployeePanelLayout.setHorizontalGroup(
            SpecificEmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SpecificEmployeePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SpecificEmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SpecificEmployeePanelLayout.createSequentialGroup()
                        .addGroup(SpecificEmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(SpecificEmployeePanelLayout.createSequentialGroup()
                                .addGroup(SpecificEmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(FirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(SpecificEmployeePanelLayout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jLabel10)))
                                .addGap(12, 12, 12)
                                .addGroup(SpecificEmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LastName, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(SpecificEmployeePanelLayout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jLabel11))))
                            .addGroup(SpecificEmployeePanelLayout.createSequentialGroup()
                                .addGroup(SpecificEmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(EmpGender, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(SpecificEmployeePanelLayout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jLabel15)))
                                .addGap(12, 12, 12)
                                .addGroup(SpecificEmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(EmpWorkLoc, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(SpecificEmployeePanelLayout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jLabel14))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SpecificEmployeePanelLayout.createSequentialGroup()
                                .addGroup(SpecificEmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(NetIncome, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(SpecificEmployeePanelLayout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jLabel13)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(SpecificEmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(DeductRate, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(SpecificEmployeePanelLayout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jLabel17)))))
                        .addGroup(SpecificEmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(SpecificEmployeePanelLayout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addGroup(SpecificEmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(EmpType, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(EmpRole, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(SpecificEmployeePanelLayout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addGroup(SpecificEmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel12)
                                            .addComponent(jLabel16)))))
                            .addGroup(SpecificEmployeePanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(FTEPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(PTEPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        SpecificEmployeePanelLayout.setVerticalGroup(
            SpecificEmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SpecificEmployeePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SpecificEmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(SpecificEmployeePanelLayout.createSequentialGroup()
                        .addGroup(SpecificEmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(SpecificEmployeePanelLayout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(FirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SpecificEmployeePanelLayout.createSequentialGroup()
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(EmpType, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(SpecificEmployeePanelLayout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LastName, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(SpecificEmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(SpecificEmployeePanelLayout.createSequentialGroup()
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(EmpGender, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(SpecificEmployeePanelLayout.createSequentialGroup()
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(EmpWorkLoc, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(SpecificEmployeePanelLayout.createSequentialGroup()
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(EmpRole, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PTEPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(SpecificEmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(SpecificEmployeePanelLayout.createSequentialGroup()
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DeductRate, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(SpecificEmployeePanelLayout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NetIncome, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(FTEPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(SpecificEmployeePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SpecificEmployeePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DisplayEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisplayEmployeeActionPerformed
        // TODO add your handling code here:
        if (userInput.getText().equals("")){
            noEmployeeFound.setVisible(true);
        }
        else{
            noEmployeeFound.setVisible(false);
            int employeeNumber = Integer.parseInt(userInput.getText());
            EmployeeInfo DisplayEmployee = theMainHashTable.searchFromTable(employeeNumber);

            if(DisplayEmployee != null){

                SpecificEmployeePanel.setVisible(true);

                FirstName.setText(DisplayEmployee.getFirstName());
                LastName.setText(DisplayEmployee.getLastName());
                DeductRate.setText(Double.toString(DisplayEmployee.getDeductRate()));

                if (DisplayEmployee.getGender() == 0){
                    EmpGender.setText("Male");
                }

                if (DisplayEmployee.getGender() == 1){
                    EmpGender.setText("Female");
                }

                if (DisplayEmployee.getGender() == 2){
                    EmpGender.setText("Other");
                }

                if (DisplayEmployee.getWorkLoc() == 0){
                    EmpWorkLoc.setText("Mississauga");
                }

                if (DisplayEmployee.getWorkLoc() == 1){
                    EmpWorkLoc.setText("Brampton");
                }

                if (DisplayEmployee.getWorkLoc() == 2){
                    EmpWorkLoc.setText("Oakville");
                }

                if (DisplayEmployee.getWorkLoc() == 3){
                    EmpWorkLoc.setText("Toronto");
                }

                if (DisplayEmployee.getEmpRole() == 0){
                    EmpRole.setText("Hardware");
                }

                if (DisplayEmployee.getEmpRole() == 1){
                    EmpRole.setText("Software");
                }

                if (DisplayEmployee.getEmpRole() == 2){
                    EmpRole.setText("Manager");
                }

                if (DisplayEmployee instanceof FTE) {
                    DisplayEmployeeFTE = (FTE) DisplayEmployee;
                    EmpType.setText("FTE");
                    NetIncome.setText(Double.toString(DisplayEmployeeFTE.calcNetAnnualIncome()));
                    FTEPanel.setVisible(true);
                    PTEPanel.setVisible(false);
                    YearlySalary.setText(Double.toString(DisplayEmployeeFTE.getYearlySalary()));

                }

                if(DisplayEmployee instanceof PTE) {
                    DisplayEmployeePTE = (PTE) DisplayEmployee;
                    EmpType.setText("PTE");
                    NetIncome.setText(Double.toString(DisplayEmployeePTE.calcNetAnnualIncome()));
                    PTEPanel.setVisible(true);
                    FTEPanel.setVisible(false);
                    HW.setText(Double.toString(DisplayEmployeePTE.getHourlyWage()));
                    HPW.setText(Double.toString(DisplayEmployeePTE.getHoursPerWeek()));
                    WPY.setText(Double.toString(DisplayEmployeePTE.getWeeksPerYear()));
                }
            }
            else{
                noEmployeeFound.setVisible(true);
            }
        }

    }//GEN-LAST:event_DisplayEmployeeActionPerformed

    private void ExitProgramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitProgramActionPerformed
        // TODO add your handling code here:
        dispose();
        theMainHashTable.saveFile("HTarchive.txt");
    }//GEN-LAST:event_ExitProgramActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DisplaySpecificEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DisplaySpecificEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DisplaySpecificEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DisplaySpecificEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DisplaySpecificEmployee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField DeductRate;
    private javax.swing.JButton DisplayEmployee;
    private javax.swing.JTextField EmpGender;
    private javax.swing.JTextField EmpRole;
    private javax.swing.JTextField EmpType;
    private javax.swing.JTextField EmpWorkLoc;
    private javax.swing.JButton ExitProgram;
    private javax.swing.JPanel FTEPanel;
    private javax.swing.JTextField FirstName;
    private javax.swing.JTextField HPW;
    private javax.swing.JTextField HW;
    private javax.swing.JTextField LastName;
    private javax.swing.JTextField NetIncome;
    private javax.swing.JPanel PTEPanel;
    private javax.swing.JPanel SpecificEmployeePanel;
    private javax.swing.JTextField WPY;
    private javax.swing.JLabel WPYLabel;
    private javax.swing.JTextField YearlySalary;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel noEmployeeFound;
    private javax.swing.JTextField userInput;
    // End of variables declaration//GEN-END:variables
}
