/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author krishchandarana
 */
public class EditEmployee extends javax.swing.JFrame {

    private MyHashTable theMainHashTable;
    private int employeeGender;
    private int employeeWorkLocation;
    private int employeeRole;
    private int employeeType;
    private EmployeeInfo employeeEdited;
    private FTE EditedEmployeeFTE;
    private PTE EditedEmployeePTE;
    private EmployeeInfo employeeRemoved;
    
    public void setTheMainHashTable(MyHashTable theRefValueHT){
        theMainHashTable = theRefValueHT; 
    }
    
    public EditEmployee() {
        initComponents();
        noEmployeeFound.setVisible(false);
        EmployeeEditingPanel.setVisible(false);
        FullTimePanel.setVisible(false);
        PartTimePanel.setVisible(false);
        employeeAdded.setVisible(false);
        employeeNotAdded.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        genderButtonGroup = new javax.swing.ButtonGroup();
        workLocButtonGroup = new javax.swing.ButtonGroup();
        empTypeButtonGroup = new javax.swing.ButtonGroup();
        positionButtonGroup = new javax.swing.ButtonGroup();
        jPanel5 = new javax.swing.JPanel();
        userInput = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        DisplayEmployee = new javax.swing.JButton();
        noEmployeeFound = new javax.swing.JLabel();
        BackWithoutEdit = new javax.swing.JButton();
        EmployeeEditingPanel = new javax.swing.JPanel();
        HardwareButton = new javax.swing.JRadioButton();
        SoftwareButton = new javax.swing.JRadioButton();
        ManagerButton = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        MississaugaButton = new javax.swing.JRadioButton();
        OakvilleButton = new javax.swing.JRadioButton();
        TorontoButton = new javax.swing.JRadioButton();
        BramptonButton = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        MaleButton = new javax.swing.JRadioButton();
        FemaleButton = new javax.swing.JRadioButton();
        OtherButton = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        InputEmpNum = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        FullTimeButton = new javax.swing.JRadioButton();
        PartTimeButton = new javax.swing.JRadioButton();
        PartTimePanel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        InputHourWage = new javax.swing.JTextField();
        InputHoursWeek = new javax.swing.JTextField();
        InputWeeksYear = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        FullTimePanel = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        InputYearlySalary = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        ExitProgram = new javax.swing.JButton();
        addEmployee = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        InputDR1 = new javax.swing.JTextField();
        InputLastName = new javax.swing.JTextField();
        InputFirstName = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        employeeAdded = new javax.swing.JLabel();
        employeeNotAdded = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 99, 71)));

        userInput.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jLabel8.setText("Enter Employee Number Below:");

        DisplayEmployee.setBackground(new java.awt.Color(255, 255, 255));
        DisplayEmployee.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        DisplayEmployee.setText("Display Employee");
        DisplayEmployee.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 99, 71), 1, true));
        DisplayEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisplayEmployeeActionPerformed(evt);
            }
        });

        noEmployeeFound.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        noEmployeeFound.setText("*CANNOT FIND EMPLOYEE*");

        BackWithoutEdit.setBackground(new java.awt.Color(255, 255, 255));
        BackWithoutEdit.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        BackWithoutEdit.setText("Back");
        BackWithoutEdit.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 99, 71), 1, true));
        BackWithoutEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackWithoutEditActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(userInput, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel8))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(noEmployeeFound)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(DisplayEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(BackWithoutEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(userInput, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DisplayEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BackWithoutEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(noEmployeeFound)
                .addGap(155, 155, 155))
        );

        EmployeeEditingPanel.setBackground(new java.awt.Color(255, 255, 255));

        HardwareButton.setBackground(new java.awt.Color(255, 255, 255));
        positionButtonGroup.add(HardwareButton);
        HardwareButton.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        HardwareButton.setText("Hardware");
        HardwareButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HardwareButtonActionPerformed(evt);
            }
        });

        SoftwareButton.setBackground(new java.awt.Color(255, 255, 255));
        positionButtonGroup.add(SoftwareButton);
        SoftwareButton.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        SoftwareButton.setText("Software");
        SoftwareButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SoftwareButtonActionPerformed(evt);
            }
        });

        ManagerButton.setBackground(new java.awt.Color(255, 255, 255));
        positionButtonGroup.add(ManagerButton);
        ManagerButton.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        ManagerButton.setText("Manager");
        ManagerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManagerButtonActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel2.setText("Position:");

        jLabel3.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel3.setText("Location:");

        MississaugaButton.setBackground(new java.awt.Color(255, 255, 255));
        workLocButtonGroup.add(MississaugaButton);
        MississaugaButton.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        MississaugaButton.setText("Mississuaga");
        MississaugaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MississaugaButtonActionPerformed(evt);
            }
        });

        OakvilleButton.setBackground(new java.awt.Color(255, 255, 255));
        workLocButtonGroup.add(OakvilleButton);
        OakvilleButton.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        OakvilleButton.setText("Oakville");
        OakvilleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OakvilleButtonActionPerformed(evt);
            }
        });

        TorontoButton.setBackground(new java.awt.Color(255, 255, 255));
        workLocButtonGroup.add(TorontoButton);
        TorontoButton.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        TorontoButton.setText("Toronto");
        TorontoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TorontoButtonActionPerformed(evt);
            }
        });

        BramptonButton.setBackground(new java.awt.Color(255, 255, 255));
        workLocButtonGroup.add(BramptonButton);
        BramptonButton.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        BramptonButton.setText("Brampton");
        BramptonButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BramptonButtonActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel4.setText("Gender:");

        MaleButton.setBackground(new java.awt.Color(255, 255, 255));
        genderButtonGroup.add(MaleButton);
        MaleButton.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        MaleButton.setText("Male");
        MaleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MaleButtonActionPerformed(evt);
            }
        });

        FemaleButton.setBackground(new java.awt.Color(255, 255, 255));
        genderButtonGroup.add(FemaleButton);
        FemaleButton.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        FemaleButton.setText("Female");
        FemaleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FemaleButtonActionPerformed(evt);
            }
        });

        OtherButton.setBackground(new java.awt.Color(255, 255, 255));
        genderButtonGroup.add(OtherButton);
        OtherButton.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        OtherButton.setText("Other");
        OtherButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OtherButtonActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel5.setText("Type of Employee:");

        InputEmpNum.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        InputEmpNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputEmpNumActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel6.setText("Deduction Rate:");

        FullTimeButton.setBackground(new java.awt.Color(255, 255, 255));
        empTypeButtonGroup.add(FullTimeButton);
        FullTimeButton.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        FullTimeButton.setText("Full Time");
        FullTimeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FullTimeButtonActionPerformed(evt);
            }
        });

        PartTimeButton.setBackground(new java.awt.Color(255, 255, 255));
        empTypeButtonGroup.add(PartTimeButton);
        PartTimeButton.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        PartTimeButton.setText("Part Time");
        PartTimeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PartTimeButtonActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel7.setText("Part Time:");

        InputHourWage.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        InputHourWage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputHourWageActionPerformed(evt);
            }
        });

        InputHoursWeek.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        InputHoursWeek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputHoursWeekActionPerformed(evt);
            }
        });

        InputWeeksYear.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        InputWeeksYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputWeeksYearActionPerformed(evt);
            }
        });

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jLabel13.setText("Hourly Wage:");

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jLabel14.setText("Hours Per Week:");

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jLabel15.setText("Weeks Per Year:");

        javax.swing.GroupLayout PartTimePanelLayout = new javax.swing.GroupLayout(PartTimePanel);
        PartTimePanel.setLayout(PartTimePanelLayout);
        PartTimePanelLayout.setHorizontalGroup(
            PartTimePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PartTimePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PartTimePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(InputHourWage, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(PartTimePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(InputHoursWeek, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(PartTimePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(InputWeeksYear, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        PartTimePanelLayout.setVerticalGroup(
            PartTimePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PartTimePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(13, 13, 13)
                .addGroup(PartTimePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PartTimePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InputHourWage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(InputHoursWeek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(InputWeeksYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jLabel9.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel9.setText("Full Time:");

        InputYearlySalary.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        InputYearlySalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputYearlySalaryActionPerformed(evt);
            }
        });

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jLabel16.setText("Yearly Salary:");

        javax.swing.GroupLayout FullTimePanelLayout = new javax.swing.GroupLayout(FullTimePanel);
        FullTimePanel.setLayout(FullTimePanelLayout);
        FullTimePanelLayout.setHorizontalGroup(
            FullTimePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FullTimePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(FullTimePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(InputYearlySalary, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addContainerGap(334, Short.MAX_VALUE))
        );
        FullTimePanelLayout.setVerticalGroup(
            FullTimePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FullTimePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addGap(19, 19, 19)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(InputYearlySalary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jTextField5.setBackground(new java.awt.Color(255, 99, 71));

        ExitProgram.setBackground(new java.awt.Color(255, 255, 255));
        ExitProgram.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        ExitProgram.setText("Back");
        ExitProgram.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 99, 71), 1, true));
        ExitProgram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitProgramActionPerformed(evt);
            }
        });

        addEmployee.setBackground(new java.awt.Color(255, 255, 255));
        addEmployee.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        addEmployee.setText("Add Employee");
        addEmployee.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 99, 71), 1, true));
        addEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addEmployeeActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel10.setText("Employee Number:");

        jLabel11.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel11.setText("First Name:");

        jLabel12.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel12.setText("Last Name:");

        InputDR1.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        InputDR1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputDR1ActionPerformed(evt);
            }
        });

        InputLastName.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        InputLastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputLastNameActionPerformed(evt);
            }
        });

        InputFirstName.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        InputFirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputFirstNameActionPerformed(evt);
            }
        });

        jLabel17.setBackground(new java.awt.Color(255, 255, 255));
        jLabel17.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jLabel17.setText("Please enter DR as a decimal value.");

        employeeAdded.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        employeeAdded.setText("Employee Succesfully Added!");

        employeeNotAdded.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        employeeNotAdded.setText("*DUPLICATE EMPLOYEE NUMBER OR FILL  OUT ALL FIELDS*");

        javax.swing.GroupLayout EmployeeEditingPanelLayout = new javax.swing.GroupLayout(EmployeeEditingPanel);
        EmployeeEditingPanel.setLayout(EmployeeEditingPanelLayout);
        EmployeeEditingPanelLayout.setHorizontalGroup(
            EmployeeEditingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EmployeeEditingPanelLayout.createSequentialGroup()
                .addGroup(EmployeeEditingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EmployeeEditingPanelLayout.createSequentialGroup()
                        .addGroup(EmployeeEditingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(InputEmpNum, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(EmployeeEditingPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel10)))
                        .addGap(12, 12, 12)
                        .addGroup(EmployeeEditingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(EmployeeEditingPanelLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(InputFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37))
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(9, 9, 9)
                        .addGroup(EmployeeEditingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(InputLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)))
                    .addGroup(EmployeeEditingPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(EmployeeEditingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PartTimePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(EmployeeEditingPanelLayout.createSequentialGroup()
                                .addComponent(PartTimeButton)
                                .addGap(54, 54, 54)
                                .addComponent(FullTimeButton))
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addGroup(EmployeeEditingPanelLayout.createSequentialGroup()
                                .addComponent(HardwareButton)
                                .addGap(50, 50, 50)
                                .addComponent(SoftwareButton)
                                .addGap(53, 53, 53)
                                .addComponent(ManagerButton))
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addGroup(EmployeeEditingPanelLayout.createSequentialGroup()
                                .addGroup(EmployeeEditingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(MississaugaButton)
                                    .addComponent(MaleButton))
                                .addGap(42, 42, 42)
                                .addGroup(EmployeeEditingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(FemaleButton)
                                    .addComponent(BramptonButton))
                                .addGap(47, 47, 47)
                                .addGroup(EmployeeEditingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(OtherButton)
                                    .addGroup(EmployeeEditingPanelLayout.createSequentialGroup()
                                        .addComponent(OakvilleButton)
                                        .addGap(18, 18, 18)
                                        .addComponent(TorontoButton))))
                            .addGroup(EmployeeEditingPanelLayout.createSequentialGroup()
                                .addComponent(addEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(66, 66, 66)
                                .addComponent(ExitProgram, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(FullTimePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(InputDR1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17)
                            .addComponent(employeeAdded)
                            .addComponent(employeeNotAdded))))
                .addContainerGap(369, Short.MAX_VALUE))
        );
        EmployeeEditingPanelLayout.setVerticalGroup(
            EmployeeEditingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EmployeeEditingPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(EmployeeEditingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(EmployeeEditingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InputEmpNum, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(InputLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(InputFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(EmployeeEditingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HardwareButton)
                    .addComponent(SoftwareButton)
                    .addComponent(ManagerButton))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(EmployeeEditingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MississaugaButton)
                    .addComponent(BramptonButton)
                    .addComponent(OakvilleButton)
                    .addComponent(TorontoButton))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(EmployeeEditingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MaleButton)
                    .addComponent(FemaleButton)
                    .addComponent(OtherButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(InputDR1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(EmployeeEditingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FullTimeButton)
                    .addComponent(PartTimeButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PartTimePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FullTimePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(EmployeeEditingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(addEmployee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ExitProgram, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(employeeNotAdded)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(employeeAdded)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(EmployeeEditingPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(EmployeeEditingPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DisplayEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisplayEmployeeActionPerformed
        // TODO add your handling code here:
        if (userInput.getText().equals("")){
            noEmployeeFound.setVisible(true);
            EmployeeEditingPanel.setVisible(false);
            FullTimePanel.setVisible(false);
            PartTimePanel.setVisible(false);
        }
        else{
            noEmployeeFound.setVisible(false);

            int employeeNumber = Integer.parseInt(userInput.getText());
            EmployeeInfo employeeEdited = theMainHashTable.searchFromTable(employeeNumber);

            if(employeeEdited != null){

                EmployeeEditingPanel.setVisible(true);

                InputEmpNum.setText(Integer.toString(employeeEdited.getEmpNum()));
                InputFirstName.setText(employeeEdited.getFirstName());
                InputLastName.setText(employeeEdited.getLastName());
                InputDR1.setText(Double.toString(employeeEdited.getDeductRate()));
                
                
               
                if (employeeEdited.getGender() == 0){
                    MaleButton.setSelected(true);
                }

                if (employeeEdited.getGender() == 1){
                    FemaleButton.setSelected(true);
                }

                if (employeeEdited.getGender() == 2){
                    OtherButton.setSelected(true);
                }

                if (employeeEdited.getWorkLoc() == 0){
                    MississaugaButton.setSelected(true);
                }

                if (employeeEdited.getWorkLoc() == 1){
                    BramptonButton.setSelected(true);
                }

                if (employeeEdited.getWorkLoc() == 2){
                    OakvilleButton.setSelected(true);
                }

                if (employeeEdited.getWorkLoc() == 3){
                    TorontoButton.setSelected(true);
                }

                if (employeeEdited.getEmpRole() == 0){
                    HardwareButton.setSelected(true);
                }

                if (employeeEdited.getEmpRole() == 1){
                    SoftwareButton.setSelected(true);
                }

                if (employeeEdited.getEmpRole() == 2){
                    ManagerButton.setSelected(true);
                }

                if (employeeEdited instanceof FTE) {
                    EditedEmployeeFTE = (FTE) employeeEdited;
                    FullTimeButton.setSelected(true);
                    FullTimePanel.setVisible(true);
                    PartTimePanel.setVisible(false);
                    employeeAdded.setVisible(false);
                    FullTimeButton.doClick();
                    InputYearlySalary.setText(Double.toString(EditedEmployeeFTE.getYearlySalary()));
                    

                    //Resets the PTE panel incase they switch employee Type
                    InputHoursWeek.setText("");
                    InputHourWage.setText("");
                    InputWeeksYear.setText("");

                }

                if(employeeEdited instanceof PTE) {
                    EditedEmployeePTE = (PTE) employeeEdited;
                    PartTimeButton.setSelected(true);
                    PartTimePanel.setVisible(true);
                    FullTimePanel.setVisible(false);
                    employeeAdded.setVisible(false);
                 
                    PartTimeButton.doClick();
               
                    InputHoursWeek.setText(Double.toString(EditedEmployeePTE.getHourlyWage()));
                    InputHourWage.setText(Double.toString(EditedEmployeePTE.getHoursPerWeek()));
                    InputWeeksYear.setText(Double.toString(EditedEmployeePTE.getWeeksPerYear()));
                   


                    //Resets the FTE panel incase they switch employee Type
                    InputYearlySalary.setText("");
                }
            }
            else{
                //if there is no such employee in the table
                noEmployeeFound.setVisible(true);
                EmployeeEditingPanel.setVisible(false);
            }
        }
    }//GEN-LAST:event_DisplayEmployeeActionPerformed

    private void BackWithoutEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackWithoutEditActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_BackWithoutEditActionPerformed

    private void HardwareButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HardwareButtonActionPerformed
        // TODO add your handling code here:
        employeeRole = 0;
    }//GEN-LAST:event_HardwareButtonActionPerformed

    private void SoftwareButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SoftwareButtonActionPerformed
        // TODO add your handling code here:
        employeeRole = 1;
    }//GEN-LAST:event_SoftwareButtonActionPerformed

    private void ManagerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManagerButtonActionPerformed
        // TODO add your handling code here:
        employeeRole = 2;
    }//GEN-LAST:event_ManagerButtonActionPerformed

    private void MississaugaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MississaugaButtonActionPerformed
        // TODO add your handling code here:
        employeeWorkLocation = 0;
    }//GEN-LAST:event_MississaugaButtonActionPerformed

    private void OakvilleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OakvilleButtonActionPerformed
        // TODO add your handling code here:
        employeeWorkLocation = 2;
    }//GEN-LAST:event_OakvilleButtonActionPerformed

    private void TorontoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TorontoButtonActionPerformed
        // TODO add your handling code here:
        employeeWorkLocation = 3;
    }//GEN-LAST:event_TorontoButtonActionPerformed

    private void BramptonButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BramptonButtonActionPerformed
        // TODO add your handling code here:
        employeeWorkLocation = 1;
    }//GEN-LAST:event_BramptonButtonActionPerformed

    private void MaleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MaleButtonActionPerformed
        // TODO add your handling code here:
        employeeGender = 0;
    }//GEN-LAST:event_MaleButtonActionPerformed

    private void FemaleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FemaleButtonActionPerformed
        // TODO add your handling code here:
        employeeGender = 1;
    }//GEN-LAST:event_FemaleButtonActionPerformed

    private void OtherButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OtherButtonActionPerformed
        // TODO add your handling code here:
        employeeGender = 2;
    }//GEN-LAST:event_OtherButtonActionPerformed

    private void InputEmpNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputEmpNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputEmpNumActionPerformed

    private void FullTimeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FullTimeButtonActionPerformed
        // TODO add your handling code here:
        FullTimePanel.setVisible(true);
        PartTimePanel.setVisible(false);
        employeeType = 1;
    }//GEN-LAST:event_FullTimeButtonActionPerformed

    private void PartTimeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PartTimeButtonActionPerformed
        // TODO add your handling code here:
        FullTimePanel.setVisible(false);
        PartTimePanel.setVisible(true);
        employeeType = 0;
    }//GEN-LAST:event_PartTimeButtonActionPerformed

    private void InputHourWageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputHourWageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputHourWageActionPerformed

    private void InputHoursWeekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputHoursWeekActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputHoursWeekActionPerformed

    private void InputWeeksYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputWeeksYearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputWeeksYearActionPerformed

    private void InputYearlySalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputYearlySalaryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputYearlySalaryActionPerformed

    private void ExitProgramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitProgramActionPerformed
        // TODO add your handling code here:
        dispose();
        theMainHashTable.saveFile("HTarchive.txt");
    }//GEN-LAST:event_ExitProgramActionPerformed

    private void addEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addEmployeeActionPerformed
        // TODO add your handling code here:
        //The employee is added to the hash table
        PTE thePTE;
        FTE theFTE;
        
        int empNumRemove = Integer.parseInt(userInput.getText());
        employeeRemoved = theMainHashTable.removeEmployee(empNumRemove);
         
        //checking if the inputs using textfields are null
        if ("".equals(InputEmpNum.getText()) || "".equals(InputFirstName.getText()) || "".equals(InputLastName.getText()) || "".equals(InputDR1.getText())) {
            employeeNotAdded.setVisible(true);
        }
        else {
            employeeNotAdded.setVisible(false);

            int theNewEmployeeNumber = Integer.parseInt(InputEmpNum.getText());
            EmployeeInfo checkIfInTable = theMainHashTable.searchFromTable(theNewEmployeeNumber);

            //Input For Each Text Field
            //Input For employee number
            String employeeNumberString = InputEmpNum.getText();
            int employeeNumber = Integer.parseInt(employeeNumberString);

            //Input For first name
            String employeeFirstName = InputFirstName.getText();

            //Input For last name
            String employeeLastName = InputLastName.getText();

            //Input For Deduction Rate
            String employeeDeductString = InputDR1.getText();
            double employeeDR = Double.parseDouble(employeeDeductString);

            if (employeeType == 0) {//Assigned to add PTE
                if (checkIfInTable != null || "".equals(InputHourWage.getText()) || "".equals(InputHoursWeek.getText()) || "".equals(InputWeeksYear.getText())){ //checks if each textfield in PTE is empty
                    employeeNotAdded.setVisible(true);
                    employeeAdded.setVisible(false);
                    theMainHashTable.addEmployee(employeeRemoved);
                    employeeRemoved = null;
                }
                else {
                    employeeNotAdded.setVisible(false);

                    //Input for hour wage
                    String employeeHWstring = InputHourWage.getText();
                    double employeeHW = Double.parseDouble(employeeHWstring);

                    //Input for hours per week
                    String employeeHPWstring = InputHoursWeek.getText();
                    double employeeHPW = Double.parseDouble(employeeHPWstring);

                    //Input for weeks per year
                    String employeeWPYstring = InputWeeksYear.getText();
                    double employeeWPY = Double.parseDouble(employeeWPYstring);

                    //addes the employee given it is a PTE
                    thePTE = new PTE(employeeNumber, employeeFirstName, employeeLastName, employeeGender, employeeWorkLocation, employeeRole, employeeDR, employeeHW, employeeHPW, employeeWPY);
                    theMainHashTable.addEmployee(thePTE);
                    employeeAdded.setVisible(true);
                }
            }
            
            if (employeeType == 1){//Assigned to add FTE
                if (checkIfInTable != null || "".equals(InputYearlySalary.getText())){ //checks if each textfield in FTE is empty
                    employeeNotAdded.setVisible(true);
                    employeeAdded.setVisible(false);
                    theMainHashTable.addEmployee(employeeRemoved);
                    employeeRemoved = null;
                }
                else {
                    employeeNotAdded.setVisible(false);

                    //Input for yearly salary
                    String employeeYSstring = InputYearlySalary.getText();
                    double employeeYS = Double.parseDouble(employeeYSstring);

                    //addes the employee given it is a PTE
                    theFTE = new FTE(employeeNumber, employeeFirstName, employeeLastName, employeeGender, employeeWorkLocation, employeeRole, employeeDR, employeeYS);
                    theMainHashTable.addEmployee(theFTE);
                    employeeAdded.setVisible(true);
                }
            }
        }
    }//GEN-LAST:event_addEmployeeActionPerformed

    private void InputDR1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputDR1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputDR1ActionPerformed

    private void InputLastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputLastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputLastNameActionPerformed

    private void InputFirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputFirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputFirstNameActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditEmployee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackWithoutEdit;
    private javax.swing.JRadioButton BramptonButton;
    private javax.swing.JButton DisplayEmployee;
    private javax.swing.JPanel EmployeeEditingPanel;
    private javax.swing.JButton ExitProgram;
    private javax.swing.JRadioButton FemaleButton;
    private javax.swing.JRadioButton FullTimeButton;
    private javax.swing.JPanel FullTimePanel;
    private javax.swing.JRadioButton HardwareButton;
    private javax.swing.JTextField InputDR1;
    private javax.swing.JTextField InputEmpNum;
    private javax.swing.JTextField InputFirstName;
    private javax.swing.JTextField InputHourWage;
    private javax.swing.JTextField InputHoursWeek;
    private javax.swing.JTextField InputLastName;
    private javax.swing.JTextField InputWeeksYear;
    private javax.swing.JTextField InputYearlySalary;
    private javax.swing.JRadioButton MaleButton;
    private javax.swing.JRadioButton ManagerButton;
    private javax.swing.JRadioButton MississaugaButton;
    private javax.swing.JRadioButton OakvilleButton;
    private javax.swing.JRadioButton OtherButton;
    private javax.swing.JRadioButton PartTimeButton;
    private javax.swing.JPanel PartTimePanel;
    private javax.swing.JRadioButton SoftwareButton;
    private javax.swing.JRadioButton TorontoButton;
    private javax.swing.JButton addEmployee;
    private javax.swing.ButtonGroup empTypeButtonGroup;
    private javax.swing.JLabel employeeAdded;
    private javax.swing.JLabel employeeNotAdded;
    private javax.swing.ButtonGroup genderButtonGroup;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JLabel noEmployeeFound;
    private javax.swing.ButtonGroup positionButtonGroup;
    private javax.swing.JTextField userInput;
    private javax.swing.ButtonGroup workLocButtonGroup;
    // End of variables declaration//GEN-END:variables
}
