/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.io.FileReader;
import java.io.IOException;
import java.util.logging.Logger;
import java.util.logging.Level;
import java.io.BufferedReader;
import java.io.FileNotFoundException;

/**
 *
 * @author krishchandarana
 */
public class MainJFrame extends javax.swing.JFrame {

    private MyHashTable theHT;
    
    public MainJFrame() {
        initComponents();
        jPanel2.setVisible(false);
        jPanel3.setVisible(true);
        InncorectPassword.setVisible(false);
        theHT = new MyHashTable(10); 
        
        // the archived hash table is loaded when the application starts
         try {
            loadFile("HTarchive.txt");
        } catch (IOException e) {
            Logger.getLogger(MainJFrame.class.getName()).log(Level.SEVERE, null, e);
        }   
       
    }
    
    public MyHashTable getTheHashTable () {
        return theHT;
       
    }
    
    public void loadFile(String theFileLocation) throws IOException{
        FTE theFTE;
        PTE thePTE;
        String theline;
        theHT = new MyHashTable(10);
        
        try {
            //Loads employee and reads info to add to hashtable
            BufferedReader FileArchive = new BufferedReader(new FileReader(theFileLocation));
            while(true){
                
                theline = FileArchive.readLine();
                String info[] = theline.split("\\*");
                
                //adds a full time employee
                if ("FTE".equals(info[0])) {
                    //info[0] we know is "FTE" or "PTE" - if it is FTE it will add a PTE employee
                    theFTE = new FTE(Integer.parseInt(info[1]), info[2], info[3], Integer.parseInt(info[4]), Integer.parseInt(info[5]), Integer.parseInt(info[6]), Double.parseDouble(info[7]), Double.parseDouble(info[8]));
                    theHT.addEmployee(theFTE);
                    
                    //iterates through the data and displays 
                    for (int i = 0; i <= 7; i++) {
                        System.out.println(info[i]);
                    }
                }
                
                //adds a part time employee
                if ("PTE".equals(info[0])) {
                      //info[0] we know is "FTE" or "PTE" - if it is PTE it will add a PTE employee
                    thePTE = new PTE(Integer.parseInt(info[1]), info[2], info[3], Integer.parseInt(info[4]), Integer.parseInt(info[5]), Integer.parseInt(info[6]), Double.parseDouble(info[7]), Double.parseDouble(info[8]), Double.parseDouble(info[9]), Double.parseDouble(info[10]));
                    theHT.addEmployee(thePTE);
                   
                    
                    //iterates through the data and displays  
                    for (int i = 0; i <= 9; i++) {
                        System.out.println(info[i]);
                    }
                }
                
                // tells the program where the end of the file is
                if("$$$$$$$".equals(info[0])){
                   break; 
                   
                }
            }
      
        } catch (FileNotFoundException nothing) {// if there is no existing data to import
            Logger.getLogger(MainJFrame.class.getName()).log(Level.SEVERE, null, nothing);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        EditEmployee = new javax.swing.JButton();
        ExitProgram = new javax.swing.JButton();
        DisplayAllEmployee = new javax.swing.JButton();
        RemoveEmployee = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        AddEmployee = new javax.swing.JButton();
        DisplaySpecificEmployee = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        LogIn = new javax.swing.JButton();
        InncorectPassword = new javax.swing.JLabel();
        userInput = new javax.swing.JPasswordField();
        showPassword = new javax.swing.JCheckBox();
        ExitProgramFully = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel1.setText("Employee Management System");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        EditEmployee.setBackground(new java.awt.Color(255, 255, 255));
        EditEmployee.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        EditEmployee.setText("Edit Employee");
        EditEmployee.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 99, 71), 1, true));
        EditEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditEmployeeActionPerformed(evt);
            }
        });

        ExitProgram.setBackground(new java.awt.Color(255, 255, 255));
        ExitProgram.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        ExitProgram.setText("Exit");
        ExitProgram.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 99, 71), 1, true));
        ExitProgram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitProgramActionPerformed(evt);
            }
        });

        DisplayAllEmployee.setBackground(new java.awt.Color(255, 255, 255));
        DisplayAllEmployee.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        DisplayAllEmployee.setText("Display All Employees");
        DisplayAllEmployee.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 99, 71), 1, true));
        DisplayAllEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisplayAllEmployeeActionPerformed(evt);
            }
        });

        RemoveEmployee.setBackground(new java.awt.Color(255, 255, 255));
        RemoveEmployee.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        RemoveEmployee.setText("Remove Employee");
        RemoveEmployee.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 99, 71), 1, true));
        RemoveEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveEmployeeActionPerformed(evt);
            }
        });

        jTextField1.setBackground(new java.awt.Color(255, 99, 71));

        jTextField2.setBackground(new java.awt.Color(255, 99, 71));

        AddEmployee.setBackground(new java.awt.Color(255, 255, 255));
        AddEmployee.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        AddEmployee.setText("Add Employee");
        AddEmployee.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 99, 71), 1, true));
        AddEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddEmployeeActionPerformed(evt);
            }
        });

        DisplaySpecificEmployee.setBackground(new java.awt.Color(255, 255, 255));
        DisplaySpecificEmployee.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        DisplaySpecificEmployee.setText("Display Specific Employee");
        DisplaySpecificEmployee.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 99, 71), 1, true));
        DisplaySpecificEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisplaySpecificEmployeeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(RemoveEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(ExitProgram, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(DisplayAllEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DisplaySpecificEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(AddEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(EditEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EditEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(RemoveEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DisplayAllEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DisplaySpecificEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ExitProgram, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jLabel8.setText("If You Do Not Know Password - Go Ask The CEO (Punit & Krish).");

        LogIn.setBackground(new java.awt.Color(255, 255, 255));
        LogIn.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        LogIn.setText("Log In");
        LogIn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 99, 71), 1, true));
        LogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogInActionPerformed(evt);
            }
        });

        InncorectPassword.setBackground(new java.awt.Color(255, 255, 255));
        InncorectPassword.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        InncorectPassword.setText("**Wrong Password!**");

        showPassword.setText("Show Password");
        showPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showPasswordActionPerformed(evt);
            }
        });

        ExitProgramFully.setBackground(new java.awt.Color(255, 255, 255));
        ExitProgramFully.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        ExitProgramFully.setText("Exit");
        ExitProgramFully.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 99, 71), 1, true));
        ExitProgramFully.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitProgramFullyActionPerformed(evt);
            }
        });

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jLabel9.setText("Enter The Manager Password Below:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(InncorectPassword)
                    .addComponent(jLabel9)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(userInput, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(showPassword))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(LogIn, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ExitProgramFully, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userInput, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(showPassword))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LogIn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ExitProgramFully, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(InncorectPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EditEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditEmployeeActionPerformed
        // TODO add your handling code here:
        EditEmployee executeEditEmployee = new EditEmployee();
        executeEditEmployee.setVisible(true);
        executeEditEmployee.setTheMainHashTable(getTheHashTable());
        // labels appearance
    }//GEN-LAST:event_EditEmployeeActionPerformed

    private void ExitProgramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitProgramActionPerformed
        // TODO add your handling code here:
        theHT.saveFile("HTarchive.txt");
        System.exit(0);
    }//GEN-LAST:event_ExitProgramActionPerformed

    private void DisplayAllEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisplayAllEmployeeActionPerformed
        // TODO add your handling code here:
        try{//loads the archived data file
            loadFile("HTarchive.txt");
        }
        catch (IOException nothing2){//if error occurs in loading the file, means cannot load any existing data
            Logger.getLogger(MainJFrame.class.getName()).log(Level.SEVERE, null, nothing2);
        }
        DisplayAllEmployee executeDisplayEmployee = new DisplayAllEmployee();
        executeDisplayEmployee.setVisible(true);
        executeDisplayEmployee.setTheMainHashTable(getTheHashTable());
    }//GEN-LAST:event_DisplayAllEmployeeActionPerformed

    private void RemoveEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveEmployeeActionPerformed
        // TODO add your handling code here:
        RemoveEmployee executeRemoveEmployee = new RemoveEmployee();
        executeRemoveEmployee.setVisible(true);
        executeRemoveEmployee.setTheMainHashTable(getTheHashTable());
    }//GEN-LAST:event_RemoveEmployeeActionPerformed

    private void AddEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddEmployeeActionPerformed
        // TODO add your handling code here:
        AddEmployee executeAddingEmployee = new AddEmployee();
        executeAddingEmployee.setVisible(true);
        executeAddingEmployee.setTheMainHashTable(getTheHashTable());
    }//GEN-LAST:event_AddEmployeeActionPerformed

    private void DisplaySpecificEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisplaySpecificEmployeeActionPerformed
        // TODO add your handling code here:
        try{//loads the archived data file
            loadFile("HTarchive.txt");
        }
        catch (IOException nothing2){//if error occurs in loading the file, means cannot load any existing data
            Logger.getLogger(MainJFrame.class.getName()).log(Level.SEVERE, null, nothing2);
        }
        DisplaySpecificEmployee executeDisplayEmployee = new DisplaySpecificEmployee();
        executeDisplayEmployee.setVisible(true);
        executeDisplayEmployee.setTheMainHashTable(getTheHashTable());
    }//GEN-LAST:event_DisplaySpecificEmployeeActionPerformed

    private void LogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogInActionPerformed
        // TODO add your handling code here:
        String Password = userInput.getText();
        if (Password.equalsIgnoreCase("duttonisthebest")){
            jPanel2.setVisible(true);
            jPanel3.setVisible(false);
        } else{
            jPanel2.setVisible(false);
            jPanel3.setVisible(true);
            InncorectPassword.setVisible(true);
        }
    }//GEN-LAST:event_LogInActionPerformed

    private void showPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showPasswordActionPerformed
        // TODO add your handling code here:
        if (showPassword.isSelected()){
            userInput.setEchoChar((char) 0);
        } else{
            userInput.setEchoChar('*');
        }
    }//GEN-LAST:event_showPasswordActionPerformed

    private void ExitProgramFullyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitProgramFullyActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_ExitProgramFullyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddEmployee;
    private javax.swing.JButton DisplayAllEmployee;
    private javax.swing.JButton DisplaySpecificEmployee;
    private javax.swing.JButton EditEmployee;
    private javax.swing.JButton ExitProgram;
    private javax.swing.JButton ExitProgramFully;
    private javax.swing.JLabel InncorectPassword;
    private javax.swing.JButton LogIn;
    private javax.swing.JButton RemoveEmployee;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JCheckBox showPassword;
    private javax.swing.JPasswordField userInput;
    // End of variables declaration//GEN-END:variables
}
